M48
; DRILL file {KiCad (6.0.11)} date Sun Jul  9 23:55:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-09T23:55:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X-0.132Y-0.4331
X-0.132Y-1.5354
X0.9704Y-0.4331
X0.9704Y-1.5354
T0
M30
